name: My first workflow
on: [pull_request]
jobs:
  greet:
    runs-on: ubuntu-latest
    steps: 
      - name: Hello 
        run: echo "Hello World"
      - name: Goodbye
        run: echo "Good bye"